export const API_KEY = 'yAvI2rK1D7CeIixWcejyGvAMLsrWsuMqIQOQnyTK'

export const EXAMPLES = [
  { "text": "¿Qué es la célula?", "label": "Biologia" },
  { "text": "¿Cuál es la diferencia entre células procariotas y eucariotas?", "label": "Biologia" },
  { "text": "diferencia entre células vegetales y animales?", "label": "Biologia" },
  { "text": "¿Quién era Charles Darwin?", "label": "Biologia" },
  { "text": "¿Qué es la teoría de la evolución biológica?", "label": "Biologia" },
  { "text": "¿Cuál es la diferencia entre el ADN y el ARN?", "label": "Biologia" },
  { "text": "¿Qué es un gen?", "label": "Biologia" },
  { "text": "¿Qué es el código genético?", "label": "Biologia" },
  { "text": "¿Cuáles son las diferencias entre mitosis y meiosis?", "label": "Biologia" },
  { "text": "¿Qué es un ecosistema?", "label": "Biologia" },
  { "text": "¿Qué es una metáfora?", "label": "Español" },
  { "text": "¿Que es un verbo irregular?", "label": "Español" },
  { "text": "¿Que es un sustantivo?", "label": "Español" },
  { "text": "¿Cuando una palabra tiene más de un significado como se llama?", "label": "Español" },
  { "text": "¿Cuáles son los grados del adjetivo?", "label": "Español" },
  { "text": "¿Cuáles son los principales géneros literarios?", "label": "Español" },
  { "text": "¿cuando se debe usar una tilde?", "label": "Español" },
  { "text": "¿Qué es un gentilicio?", "label": "Español" },
  { "text": "¿Que lleva un resumen?", "label": "Español" },
  { "text": "¿Que lleva un ensayo?", "label": "Español" },
  { "text": "¿Qué es la fotosíntesis?\n", "label": "Biologia" },
  { "text": "Que es el sistea solar?", "label": "Biologia" },
  { "text": "Cuantos planetas hay en el sistema solar?", "label": "Biologia" },
  { "text": "Que es la ciencia?", "label": "Biologia" },
  { "text": "¿Cuántos elementos tiene y cómo se ordenan la tabla preiodica?", "label": "Biologia" },
  { "text": "¿Por qué se construyó la tabla periódica?", "label": "Biologia" },
  { "text": "¿Quién hico la tabla periódica?", "label": "Biologia" },
  { "text": "elementos naturales", "label": "Biologia" },
  { "text": "¿Cuáles son los tres grandes autores del siglo XV?\n", "label": "Español" },
  { "text": "¿Quién escribió el Quijote?", "label": "Español" },
  { "text": "¿Quién escribió cien años de soledad?", "label": "Español" },
  { "text": "Qué caracteriza al Renacimiento?", "label": "Español" },
  { "text": "como hacer un cuento?", "label": "Español" },
  { "text": "tipos de cuentos", "label": "Español" },
  { "text": "quein eres?", "label": "bot" },
  { "text": "quien sos?", "label": "bot" },
  { "text": "que haces?", "label": "bot" },
  { "text": "para que sirves?", "label": "bot" },
  { "text": "quien te programo?", "label": "bot" },
  { "text": "quien te hizo", "label": "bot" },
  { "text": "dime quien eres?", "label": "bot" },
  { "text": "¿Cómo te llamas?", "label": "bot" },
  { "text": "¿Eres una persona real?", "label": "bot" },
  { "text": "¿Cuál es tu edad?", "label": "bot" },
  { "text": "¿Puedes contarme un chiste?", "label": "bot" },
  { "text": "¿Que preguntas soportas?", "label": "bot" },
  { "text": " ", "label": "indefinido" },
  { "text": "otras cosas", "label": "indefinido" },
  { "text": "tecnologias", "label": "indefinido" },
  { "text": "chat generado", "label": "indefinido" },
  { "text": "data, informacion", "label": "indefinido" },
  { "text": "juego, interaccion", "label": "indefinido" },
  { "text": "hablame de otras cosas", "label": "indefinido" },
  { "text": "politica, ciencias", "label": "indefinido" },
  { "text": "crees en religion, psicologia, vida,", "label": "indefinido" },
  { "text": "entretenimiento, futbotll, predicciones", "label": "indefinido" },
]  