export const API_KEY = 'yAvI2rK1D7CeIixWcejyGvAMLsrWsuMqIQOQnyTK'

export const EXAMPLES = [
  { "text": "¿Qué es la célula?", "label": "Biología y Ciencia " },
  { "text": "¿Cuál es la diferencia entre células procariotas y eucariotas?", "label": "Biología y Ciencia " },
  { "text": "diferencia entre células vegetales y animales?", "label": "Biología y Ciencia " },
  { "text": "¿Quién era Charles Darwin?", "label": "Biología y Ciencia " },
  { "text": "¿Qué es la teoría de la evolución biológica?", "label": "Biología y Ciencia " },
  { "text": "¿Cuál es la diferencia entre el ADN y el ARN?", "label": "Biología y Ciencia " },
  { "text": "¿Qué es un gen?", "label": "Biología y Ciencia " },
  { "text": "¿Qué es el código genético?", "label": "Biología y Ciencia " },
  { "text": "¿Cuáles son las diferencias entre mitosis y meiosis?", "label": "Biología y Ciencia " },
  { "text": "¿Qué es un ecosistema?", "label": "Biología y Ciencia " },
  { "text": "¿Qué es una metáfora?", "label": "Español " },
  { "text": "¿Que es un verbo irregular?", "label": "Español " },
  { "text": "¿Que es un sustantivo?", "label": "Español " },
  { "text": "¿Cuando una palabra tiene más de un significado como se llama?", "label": "Español " },
  { "text": "¿Cuáles son los grados del adjetivo?", "label": "Español " },
  { "text": "¿Cuáles son los principales géneros literarios?", "label": "Español " },
  { "text": "¿cuando se debe usar una tilde?", "label": "Español " },
  { "text": "¿Qué es un gentilicio?", "label": "Español " },
  { "text": "¿Que lleva un resumen?", "label": "Español " },
  { "text": "¿Que lleva un ensayo?", "label": "Español " },
  { "text": "¿Qué es la fotosíntesis?\n", "label": "Biología y Ciencia " },
  { "text": "Que es el sistea solar?", "label": "Biología y Ciencia " },
  { "text": "Cuantos planetas hay en el sistema solar?", "label": "Biología y Ciencia " },
  { "text": "Que es la ciencia?", "label": "Biología y Ciencia " },
  { "text": "¿Cuántos elementos tiene y cómo se ordenan la tabla preiodica?", "label": "Biología y Ciencia " },
  { "text": "¿Por qué se construyó la tabla periódica?", "label": "Biología y Ciencia " },
  { "text": "¿Quién hico la tabla periódica?", "label": "Biología y Ciencia " },
  { "text": "elementos naturales", "label": "Biología y Ciencia " },
  { "text": "¿Cuáles son los tres grandes autores del siglo XV?\n", "label": "Español " },
  { "text": "¿Quién escribió el Quijote?", "label": "Español " },
  { "text": "¿Quién escribió cien años de soledad?", "label": "Español " },
  { "text": "Qué caracteriza al Renacimiento?", "label": "Español " },
  { "text": "como hacer un cuento?", "label": "Español " },
  { "text": "tipos de cuentos", "label": "Español " },
  { "text": "que es un Adjetivo, Pronombre, Adverbio, Sustantivo", "label": "Español " }
]